# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: check_perm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'check_perm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63heck_perm.proto\x12\tcheckperm\"m\n\x10\x43heckPermRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12!\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x11.checkperm.Action\"4\n\x11\x43heckPermResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t*9\n\x06\x41\x63tion\x12\x08\n\x04READ\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\x0e\n\nVOICE_JOIN\x10\x02\x12\n\n\x06MANAGE\x10\x03\x32U\n\x0bPermService\x12\x46\n\tCheckPerm\x12\x1b.checkperm.CheckPermRequest\x1a\x1c.checkperm.CheckPermResponseBI\n\x13\x63om.concordia.protoB\x0e\x43heckPermProtoP\x01Z concordia/proto/gen/go/checkpermb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'check_perm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.concordia.protoB\016CheckPermProtoP\001Z concordia/proto/gen/go/checkperm'
  _globals['_ACTION']._serialized_start=196
  _globals['_ACTION']._serialized_end=253
  _globals['_CHECKPERMREQUEST']._serialized_start=31
  _globals['_CHECKPERMREQUEST']._serialized_end=140
  _globals['_CHECKPERMRESPONSE']._serialized_start=142
  _globals['_CHECKPERMRESPONSE']._serialized_end=194
  _globals['_PERMSERVICE']._serialized_start=255
  _globals['_PERMSERVICE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
