#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROTO_DIR="$SCRIPT_DIR"
GEN_GO="$SCRIPT_DIR/gen/go"
GEN_JAVA="$SCRIPT_DIR/gen/java"

mkdir -p "$GEN_GO" "$GEN_JAVA"

# Go + gRPC stubs
protoc \
  --proto_path="$PROTO_DIR" \
  --go_out="$GEN_GO" \
  --go_opt=paths=source_relative \
  --go-grpc_out="$GEN_GO" \
  --go-grpc_opt=paths=source_relative \
  check_perm.proto

# Java message stubs (gRPC service stubs generated by services/servers via Maven plugin)
protoc \
  --proto_path="$PROTO_DIR" \
  --java_out="$GEN_JAVA" \
  check_perm.proto

echo "Stubs regenerated."
