server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/servers_db}
    username: discord
    password: discord
  flyway:
    enabled: true
    baseline-on-migrate: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: servers-svc-user-registry-v2 
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO